name: Run GIT Issue Alert

on:
  issues:
    types: [opened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: npm install sync-request
      run: npm install sync-request
    - name: Install actions core
      run: npm install @actions/core
    - name: Install actions github
      run: npm install @actions/github
    - name: run the script
      run: node gitIssueScript.js
